### PR TITLE
Add Pre Flight OPTIONS call test

### PR DESCRIPTION
**Pull request by sidzi**
This PR adds the following:
1. add options test along with a fix to get test
2. add timeout context while shutting down go server

### CODE REVIEW

**Review by Shivam010 — APPROVED** [review]
LGTM

**Comment by Shivam010** [comment]
Thanks for your contribution

Closes #15

**Comment by sidzi** [comment]
> Thanks for your contribution
> 
> Closes #15

Welcome !

Can you add `hacktoberfest-accepted` label to this PR ?

**Comment by Shivam010** [comment]
Sure 👍

**Pull request merged**
